authapp/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^@(?P<username>[\w-]+)/$', views.UserProfileView.as_view(), name='profile'),
    url(r'^@(?P<username>[\w-]+)/comments/$', views.UserComments.as_view(), name='user_comments'),
    url(r'^accounts/profile/$', views.profile_redirector, name='user_profile'),
    url(r'^accounts/profile/update/$', views.UserProfileUpdateView.as_view(), name='user_profile_update'),
]

blog/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.HomeTemplateView.as_view(), name='home'),
    url(r'^@(?P<username>[\w-]+)/blog/$', views.BlogDetail.as_view(), name='user_blog'),  # noqa
    url(r'^@(?P<username>[\w-]+)/blog/(?P<slug>[\w-]+)/$',
        views.PostDetailView.as_view(), name='post_detail'),

    url(r'^tags/$', views.TagAutoComplete.as_view(), name='tag_autocomplete'),
    url(r'^tags/(?P<tag>[\w-]+)/$', views.TagggedPostsList.as_view(),
        name='tagged_posts_list'),

    url(r'^blog/start/$', views.BlogCreateView.as_view(), name='blog_create'),
    url(r'^blog/update/$', views.BlogUpdateView.as_view(), name='blog_update'),

    url(r'^blog/comments/$', views.BlogComments.as_view(), name='blog_comments'),  # noqa

    url(r'^write/$', views.PostCreateView.as_view(), name='post_create'),
    url(r'^update/(?P<slug>[\w-]+)/$', views.PostUpdateView.as_view(), name='post_update'),  # noqa
    url(r'^delete/(?P<slug>[\w-]+)/$', views.PostDeleteView.as_view(), name='post_delete'),  # noqa

    url(r'^posts/$', views.UserPostsList.as_view(), name='user_posts'),
]

medifeed/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^simplemde/', include('simplemde.urls', namespace='simplemde')),
    url(r'^comments/', include('comments.urls', namespace='comments')),
    url(r'^', include('authapp.urls', namespace='authapp')),
    url(r'^', include('blog.urls', namespace='blog')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # noqa

authapp/models.py
from django.db import models
from django.conf import settings
from django.core.urlresolvers import reverse


class UserProfile(models.Model):

    USER_TYPES = (
        ('b', 'Blogger'),
        ('r', 'Reader')
    )

    user = models.OneToOneField(settings.AUTH_USER_MODEL,
                                related_name='profile')
    avatar = models.ImageField(blank=True)
    about = models.TextField(blank=True)
    user_type = models.CharField(max_length=1, choices=USER_TYPES, default='b')

    last_updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user.username

    def save(self, *args, **kwargs):
        if self.id and self.avatar:
            current_avatar = UserProfile.objects.get(pk=self.id).avatar
            if current_avatar != self.avatar:
                current_avatar.delete()
        super(UserProfile, self).save(*args, **kwargs)

    def get_absolute_url(self):
        target = reverse('authapp:profile', args=[self.user.username])
        return target

    def is_blogger(self):
        return self.user_type == 'b'

    def is_reader(self):
        return self.user_type == 'r'

authapp/forms.py
from django import forms
from django.contrib.auth import get_user_model

from allauth.account import forms as allauth_forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Field
from crispy_forms.bootstrap import StrictButton

from .models import UserProfile


class UserForm(forms.ModelForm):
    class Meta(object):
        model = get_user_model()
        fields = ['first_name', 'last_name']

    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        self.fields['last_name'].required = False
        self.fields['first_name'].required = True
        self.helper = FormHelper(self)
        self.helper.form_tag = False
        self.helper.layout = Layout('first_name', 'last_name')


class UserProfileForm(forms.ModelForm):

    class Meta(object):
        model = UserProfile
        fields = ['about', 'avatar']

    def __init__(self, *args, **kwargs):
        super(UserProfileForm, self).__init__(*args, **kwargs)
        self.fields['avatar'].required = False
        self.fields['avatar'].label = ''
        self.helper = FormHelper(self)
        self.helper.form_tag = False
        self.helper.layout = Layout(
            Field('about', css_class='materialize-textarea'),
            Field('avatar')
        )


class CustomLoginForm(allauth_forms.LoginForm):
    def __init__(self, *args, **kwargs):
        super(CustomLoginForm, self).__init__(*args, **kwargs)
        self.fields['password'].widget = forms.PasswordInput()
        self.helper = FormHelper(self)
        self.helper.col_class = False
        self.helper.form_tag = False
        self.helper.form_show_labels = True

        for field in self.fields:
            self.fields[field].widget.attrs['placeholder'] = None
            del self.fields[field].widget.attrs['placeholder']

        self.helper.layout = Layout(
            'login', 'password', 'remember',
            StrictButton(
                'Sign In', type='submit', style='margin-top: 10px',
                css_class="waves-effect btn-large blue waves-light btn right"),
        )


class CustomChangePwdForm(allauth_forms.ChangePasswordForm):
    def __init__(self, *args, **kwargs):
        super(CustomChangePwdForm, self).__init__(*args, **kwargs)

        self.helper = FormHelper(self)
        self.helper.form_tag = False
        self.helper.form_show_labels = True

        for field in self.fields:
            self.fields[field].widget.attrs['placeholder'] = None
            del self.fields[field].widget.attrs['placeholder']

        self.helper.layout = Layout(
            'oldpassword', 'password1', 'password2',
            StrictButton(
                'Change Password', type='submit', name='action',
                css_class='btn blue waves-effect waves-light btn-large')
        )


class CustomAddEmailForm(allauth_forms.AddEmailForm):
    def __init__(self, *args, **kwargs):
        super(CustomAddEmailForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.form_tag = False
        self.helper.form_show_labels = True

        self.fields['email'].widget.attrs['placeholder'] = None
        self.fields['email'].label = 'Email Address'

        del self.fields['email'].widget.attrs['placeholder']

        self.helper.layout = Layout(
            'email',
            StrictButton(
                'Add Email', name='action_add', type='submit',
                css_class='btn blue btn-large white-text waves-effect waves-light')  # noqa
        )


class CustomResetPwdForm(allauth_forms.ResetPasswordForm):
    def __init__(self, *args, **kwargs):
        super(CustomResetPwdForm, self).__init__(*args, **kwargs)

        self.helper = FormHelper(self)
        self.helper.form_tag = False
        self.helper.form_show_labels = True

        del self.fields['email'].widget.attrs['placeholder']
        self.fields['email'].label = "Email Address"

        self.helper.layout = Layout(
            'email',
            StrictButton(
                'Reset My Password', type='submit',
                css_class='btn blue btn-large waves-effect waves-light')
        )


class CustomResetPasswordKeyForm(allauth_forms.ResetPasswordKeyForm):
    def __init__(self, *args, **kwargs):
        super(CustomResetPasswordKeyForm, self).__init__(*args, **kwargs)

        self.helper = FormHelper(self)
        self.helper.form_tag = False
        self.helper.form_show_labels = True
        for field in self.fields:
            self.fields[field].widget.attrs['placeholder'] = None
            del self.fields[field].widget.attrs['placeholder']

        self.helper.layout = Layout(
            'password1', 'password2',
            StrictButton(
                'Change Password', type='submit',
                css_class='btn blue btn-large waves-effect waves-light')
        )

authapp/views.py
import uuid

from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from django.views.generic import DetailView, ListView, UpdateView
from django.views.generic.detail import SingleObjectMixin
from django.db.models import Prefetch

from .models import UserProfile
from comments.models import Comment
from .forms import UserForm, UserProfileForm


class UserProfileView(DetailView):
    template_name = 'authapp/user_profile.html'
    model = UserProfile
    context_object_name = 'profile'
    slug_url_kwarg = 'username'
    slug_field = 'user__username'

    def get_queryset(self):
        queryset = self.model.objects.select_related(
            'user', 'user__blog').prefetch_related('user__posts')
        return queryset


@login_required
def profile_redirector(request):
    return redirect('authapp:profile', username=request.user.username)


class UserComments(SingleObjectMixin, ListView):
    template_name = 'authapp/user_comments.html'
    model = UserProfile
    slug_url_kwarg = 'username'
    slug_field = 'user__username'

    def get(self, request, *args, **kwargs):
        self.object = self.get_object(
            queryset=self.model.objects.select_related(
                'user', 'user__blog').prefetch_related(
                    Prefetch(
                        'user__comments',
                        queryset=Comment.objects.select_related(
                            'post').filter(is_public=True)
                    ),
                    'user__posts')
            )
        return super(UserComments, self).get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(UserComments, self).get_context_data(**kwargs)
        context['profile'] = self.object
        context['comments'] = self.get_queryset()
        return context

    def get_queryset(self):
        qs = self.object.user.comments.all()
        return qs


class UserProfileUpdateView(UpdateView):

    template_name = 'authapp/edit_profile.html'
    form_class = UserForm
    form_class_2 = UserProfileForm

    def get_context_data(self, **kwargs):
        context = super(UserProfileUpdateView, self).get_context_data(**kwargs)
        if 'form' not in context:
            context['form'] = self.form_class(instance=self.request.user)
        if 'form2' not in context:
            context['form2'] = self.form_class_2(instance=self.request.user.profile)  # noqa
        return context

    def get(self, request, *args, **kwargs):
        super(UserProfileUpdateView, self).get(request, *args, **kwargs)
        self.object = self.get_object()
        form = self.form_class(instance=self.request.user)
        form2 = self.form_class_2(instance=self.request.user.profile)

        return self.render_to_response(self.get_context_data(
            form=form, form2=form2
        ))

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.form_class(request.POST, instance=self.request.user)
        form2 = self.form_class_2(request.POST, request.FILES,
                                  instance=self.request.user.profile)

        if form.is_valid() and form2.is_valid():
            form.save()
            data = form2.save(commit=False)
            if request.FILES.get('avatar', None):
                data.avatar = request.FILES['avatar']
                data.avatar.name = '{0}_p.jpg'.format(str(uuid.uuid4()))
            data.save()
            return redirect('authapp:user_profile')
        else:
            return self.render_to_response(
                self.get_context_data(form=form, form2=form2)
                )

    def get_object(self, queryset=None):
        return self.request.user

templates/authapp/_user_profile_header.html
{% load staticfiles %}
<div id="profile-page-header" class="card" style="margin:0px">
  <div class="card-image" style="overflow:hidden;">
      <img class="" src="{% static 'images/user-profile-bg.jpg' %}" alt="user background">
  </div>
  <figure class="card-profile-image">
      <img
      {% if profile.avatar %}
      src="{{ profile.avatar.url }}"
      {% else %}
      src="{% static 'images/user-profile-default.jpg' %}"
      {% endif %}
      alt="profile image" class="circle z-depth-2 responsive-img">
  </figure>
  <div class="card-content" id="profile-userdetails">
    <div class="row">
      <div class="col s3 offset-s2">
          <h4 class="card-title grey-text text-darken-4">{{ profile.user.first_name }} {{ profile.user.last_name }}</h4>
          <p class="medium-small grey-text">@{{ profile.user.username }}</p>
      </div>
      <div class="col s1 center-align">
          <a href="#" title="Posts">
          <h4 class="card-title grey-text text-darken-4">{{ profile.user.posts.count }}</h4>
          <p class="medium-small grey-text"><i class="material-icons">library_books</i></p>
        </a>
      </div>
      <div class="col s1 center-align">
        <a href="{% url 'authapp:user_comments' profile.user.username %}" title="Comments">
          <h4 class="card-title grey-text text-darken-4">{{ profile.user.comments.count }}</h4>
          <p class="medium-small grey-text"><i class="material-icons">comment</i></p>
        </a>
      </div>
      <div class="col s1 center-align">
        <a href="{% url 'blog:user_blog' profile.user.username %}" title="User type">
          <h4 class="card-title grey-text text-darken-4">
            {% if profile.user.is_staff %}
              Staff
            {% else %}
              {{ profile.get_user_type_display }}
            {% endif %}
          </h4>
          <p class="medium-small grey-text">
            <i class="material-icons">
              {% if profile.user.is_staff %}
                supervisor_account
              {% elif profile.user_type == 'b' %}
                mode_edit
              {% else %}
                library_books
              {% endif %}
            </i>
          </p>
        </a>
      </div>
      {% if request.user.id == profile.user.id %}
        <div class="col s1 right-align" style="margin-top:-5px">
          <a class="btn-floating waves-effect waves-light darken-1 right"
              data-tooltip="Edit profile" href="{% url 'authapp:user_profile_update' %}">
              <i class="material-icons">mode_edit</i>
          </a>
        </div>
      {% endif %}
    </div>
  </div>
</div>

templates/authapp/edit_profile.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block head_title %}Edit profile{% endblock %}

{% block content %}
  <h3 class="center">Update Profile</h3>
  <div class="container user-page-container">
    <div class="card-panel z-depth-0">
        <form method="post" enctype="multipart/form-data" id="profileEditForm">
            {% csrf_token %}
            {% crispy form %}
            {% crispy form2 %}
            <button type="submit" value="Update Profile" class="btn btn-large blue right waves-effect waves-light">Update Profile</button>
        </form>
    </div>
  </div>
{% endblock %}

templates/authapp/user_comments.html
{% extends "base.html" %}
{% load staticfiles %}
{% block head_title %}{{ profile.user.username }}'s comments{% endblock %}
{% block content %}

  {% include "authapp/_user_profile_header.html" %}
  <div class="container">
    <h4 class="light header">Comments</h4>
    {% for comment in comments %}
      <div class="card">
        <div class="card-content">
          <a href="{{ comment.post.get_absolute_url }}">
            <span title="{{ post.title }}" class="card-title truncate">
              {{ comment.post.title }}
            </span>
          </a>
          <p>{{ comment.comment }}</p>
        </div>
        <div class="card-action">
          <a href="{{ comment.get_absolute_url }}">View on posts page.</a>
        </div>
      </div>
    {% endfor %}
  </div>
{% endblock %}

templates/authapp/user_profile.html
{% extends "base.html" %}
{% load staticfiles %}
{% load blog_tags %}
{% block head_title %}{{ profile.user.username }}'s profile{% endblock %}
{% block content %}

  {% include "authapp/_user_profile_header.html" %}

<div id="profile-page-about" class="center flow-text">
  <!-- start Profile About  -->
  <div class="card">
    <div class="card-content">
      <span class="card-title">About @{{ profile.user.username }}</span>
      {% if profile.about %}
        <p class="grey-text">{{ profile.about }}</p>
      {% else %}
      <p class="grey-text"><i>Apparently, this user prefers to keep an air of mystery about them</i>.</p>
      {% endif %}
    </div>
  </div>
  <!-- end Profile About  -->
</div>
<div class="container">
  <h4 class="light" style="border-bottom: 1px solid #eee; padding-bottom: 10px; margin-top: 30px;">
    Latest
  </h4>
  <p class="grey-text" style="font-size: 1.2em;">Recent stories from @{{ profile.user.username }}</p>
  {% latest_post profile.user as posts %}
  {% include "blog/_post_list.html" %}
{% endblock %}