blog/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.HomeTemplateView.as_view(), name='home'),
    url(r'^@(?P<username>[\w-]+)/blog/$', views.BlogDetail.as_view(), name='user_blog'),  # noqa
    url(r'^@(?P<username>[\w-]+)/blog/(?P<slug>[\w-]+)/$',
        views.PostDetailView.as_view(), name='post_detail'),

    url(r'^tags/$', views.TagAutoComplete.as_view(), name='tag_autocomplete'),
    url(r'^tags/(?P<tag>[\w-]+)/$', views.TagggedPostsList.as_view(),
        name='tagged_posts_list'),

    url(r'^blog/start/$', views.BlogCreateView.as_view(), name='blog_create'),
    url(r'^blog/update/$', views.BlogUpdateView.as_view(), name='blog_update'),

    url(r'^blog/comments/$', views.BlogComments.as_view(), name='blog_comments'),  # noqa

    url(r'^write/$', views.PostCreateView.as_view(), name='post_create'),
    url(r'^update/(?P<slug>[\w-]+)/$', views.PostUpdateView.as_view(), name='post_update'),  # noqa
    url(r'^delete/(?P<slug>[\w-]+)/$', views.PostDeleteView.as_view(), name='post_delete'),  # noqa

    url(r'^posts/$', views.UserPostsList.as_view(), name='user_posts'),
]

medifeed/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^simplemde/', include('simplemde.urls', namespace='simplemde')),
    url(r'^comments/', include('comments.urls', namespace='comments')),
    url(r'^', include('authapp.urls', namespace='authapp')),
    url(r'^', include('blog.urls', namespace='blog')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # noqa

blog/models.py
from django.db import models
from django.conf import settings
from django.core.urlresolvers import reverse_lazy

from autoslug import AutoSlugField
from simplemde.fields import SimpleMdeField


class Blog(models.Model):

    title = models.CharField(max_length=100)
    tag_line = models.CharField(max_length=50)
    short_description = models.TextField(max_length=255)

    created = models.DateTimeField(auto_now_add=True)
    last_modified = models.DateTimeField(auto_now=True)

    # one to one because an author can only have one blog (as of now)
    author = models.OneToOneField(settings.AUTH_USER_MODEL)

    is_public = models.BooleanField(default=True)
    is_deleted = models.BooleanField(default=False)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        target = reverse_lazy('blog:user_blog', args=[self.author.username])
        return target


class PostQueryset(models.QuerySet):
    """
    QuerySet class for Post model. Works like a manager.
    Useful for method chaining.
    """
    def published(self):
        return self.filter(status='p')

    def draft(self):
        return self.filter(status='d')


class Post(models.Model):

    STATUS_CHOICES = (
        ('d', 'Draft'),
        ('p', 'Published'),
    )

    blog = models.ForeignKey(Blog, related_name='posts')

    title = models.CharField(max_length=150)
    summary = models.CharField(max_length=255, blank=True)
    content = SimpleMdeField()

    slug = AutoSlugField(populate_from='title', unique_with=['blog'],
                         editable=True)

    cover = models.ImageField(blank=True, upload_to='uploads/%Y/%m/%d/')

    tags = models.ManyToManyField('Tag', related_name='posts', blank=True)

    created = models.DateTimeField(auto_now_add=True)
    last_modified = models.DateTimeField(auto_now=True)

    author = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='posts')

    status = models.CharField(choices=STATUS_CHOICES, max_length=1,
                              default='d')

    objects = PostQueryset.as_manager()

    def __str__(self):
        return self.title

    def is_published(self):
        return self.status == 'p'

    def is_draft(self):
        return self.status == 'd'

    def get_absolute_url(self):
        target = reverse_lazy('blog:post_detail',
                              args=[self.author.username, self.slug])
        return target

    class Meta(object):
        ordering = ('-created', )


class Tag(models.Model):
    name = models.CharField(max_length=30)
    slug = AutoSlugField(populate_from='name', editable=True, unique=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        target = reverse_lazy('blog:tagged_posts_list', args=[self.slug])
        return target

blog/forms.py
from django import forms

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit
from crispy_forms.bootstrap import StrictButton
from dal import autocomplete

from .models import Blog, Post, Tag


class BlogForm(forms.ModelForm):

    class Meta(object):
        model = Blog
        fields = ['title', 'tag_line', 'short_description', 'is_public']

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user')
        super(BlogForm, self).__init__(*args, **kwargs)

        # a little housekeeping
        self.fields['is_public'].label = 'Publicly visible'
        self.fields['short_description'].widget.attrs['class'] = 'materialize-textarea'  # noqa

        # making forms crispy
        self.helper = FormHelper(self)
        self.helper.layout = Layout(
            'title', 'tag_line', 'short_description', 'is_public',
            StrictButton(
                'Create a Blog', type='submit',
                css_class='btn blue btn-large right waves-effect waves-light'
            )
        )

    def save(self, commit=True):
        save_data = super(BlogForm, self).save(commit=False)
        save_data.author = self.user
        save_data.save()
        return save_data


class TagCreateField(autocomplete.CreateModelMultipleField):
    def create_value(self, value):
        return Tag.objects.create(name=value).pk


class PostForm(forms.ModelForm):
    tags = TagCreateField(
        queryset=Tag.objects.all(),
        widget=autocomplete.ModelSelect2Multiple(url='blog:tag_autocomplete'),
        required=False,
        )

    class Meta(object):
        model = Post
        fields = ['title', 'slug', 'cover', 'content', 'summary', 'tags']

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user')
        super(PostForm, self).__init__(*args, **kwargs)
        self.fields['slug'].required = False
        self.fields['slug'].label = 'Slug (leave blank to auto-generate)'
        self.fields['cover'].label = 'Post cover (optional)'
        self.fields['content'].label = ''
        # making forms crispy
        self.helper = FormHelper(self)
        self.helper.include_media = False
        self.helper.add_input(Submit(
            'draft', 'draft',
            css_class='btn orange btn-large right waves-effect waves-light'))
        self.helper.add_input(Submit(
            'publish', 'publish',
            css_class='btn blue btn-large right waves-effect waves-light'))

    def clean(self):
        cleaned_data = super(PostForm, self).clean()
        if 'publish' in self.data:
            cleaned_data['status'] = 'p'
        else:
            cleaned_data['status'] = 'd'
        return cleaned_data

    def save(self, commit=True):
        save_data = super(PostForm, self).save(commit=False)
        save_data.author = self.user
        save_data.blog = self.user.blog
        save_data.status = self.cleaned_data['status']
        save_data.save()
        return save_data

blog/views.py
from django.contrib.auth import get_user_model
from django.views.generic import (ListView, CreateView, UpdateView,
                                  DetailView, DeleteView)
from django.views.generic.detail import SingleObjectMixin
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect
from django.db.models import Count, Prefetch
from django.core.urlresolvers import reverse_lazy

from dal import autocomplete

from .models import Blog, Post, Tag
from .forms import BlogForm, PostForm
from .decorators import create_or_edit_blog, blogger_required
from comments.models import Comment


class BlogDetail(SingleObjectMixin, ListView):
    template_name = 'blog/blog_detail.html'
    slug_url_kwarg = 'username'
    slug_field = 'username'
    context_object_name = 'requested_user'

    def get(self, request, *args, **kwargs):
        UserModel = get_user_model()
        self.object = self.get_object(
            queryset=UserModel.objects.select_related().prefetch_related('blog__posts')  # noqa
        )
        return super(BlogDetail, self).get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(BlogDetail, self).get_context_data(**kwargs)
        context['requested_user'] = self.object

        try:
            context['blog'] = self.object.blog
            context['has_blog'] = True
        except Blog.DoesNotExist:
            context['has_blog'] = False

        context['posts'] = self.get_queryset()

        return context

    def get_queryset(self):
        return self.object.posts.published().annotate(comment_count=Count('comments'))   # noqa


class PostDetailView(DetailView):
    model = Post
    template_name = 'blog/post_detail.html'

    def get_queryset(self):
        queryset = Post.objects.published().select_related(
            'author', 'blog', 'author__profile').prefetch_related(
                Prefetch('comments',
                         queryset=Comment.objects.select_related(
                             'author', 'author__profile',
                             'post', 'post__author').filter(is_public=True))
            ).filter(
                author__username=self.kwargs['username'])
        return queryset


class TagggedPostsList(ListView):
    model = Post
    template_name = 'blog/tagged_posts_list.html'
    context_object_name = 'posts'

    def get_context_data(self, **kwargs):
        context = super(TagggedPostsList, self).get_context_data(**kwargs)
        context['tag'] = self.kwargs['tag']
        return context

    def get_queryset(self):
        queryset = Post.objects.published().select_related(
            'author', 'blog', 'author__profile').prefetch_related(
                'tags').annotate(
                    comment_count=Count('comments')).filter(
                        tags__slug=self.kwargs['tag'], blog__is_public=True)
        return queryset


class BlogModelMixin(object):
    model = Blog
    form_class = BlogForm

    @method_decorator([login_required, create_or_edit_blog])
    def dispatch(self, request, *args, **kwargs):
        return super(BlogModelMixin, self).dispatch(request, *args, **kwargs)

    def get_form_kwargs(self):
        kwargs = super(BlogModelMixin, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs


class BlogCreateView(BlogModelMixin, CreateView):
    template_name_suffix = '_create_form'
    success_url = reverse_lazy('authapp:user_profile')


class BlogUpdateView(BlogModelMixin, UpdateView):
    template_name_suffix = '_update_form'
    success_url = reverse_lazy('authapp:user_profile')

    def get_object(self, queryset=None):
        return self.request.user.blog


class PostModelMixin(object):
    model = Post
    form_class = PostForm
    success_url = reverse_lazy('blog:user_posts')

    @method_decorator([login_required, blogger_required])
    def dispatch(self, request, *args, **kwargs):
        return super(PostModelMixin, self).dispatch(request, *args, **kwargs)

    def get_form_kwargs(self):
        kwargs = super(PostModelMixin, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def form_valid(self, form):
        form.save()
        form.save_m2m()
        return redirect(self.success_url)


class PostCreateView(PostModelMixin, CreateView):
    template_name_suffix = '_create_form'


class PostUpdateView(PostModelMixin, UpdateView):
    template_name_suffix = '_update_form'

    def get_queryset(self):
        return self.request.user.posts.all()


class PostDeleteView(DeleteView):
    model = Post
    success_url = reverse_lazy('blog:user_posts')
    template_name_suffix = '_delete_form'

    @method_decorator([login_required, blogger_required])
    def dispatch(self, request, *args, **kwargs):
        return super(PostDeleteView, self).dispatch(request, *args, **kwargs)

    def get_queryset(self):
        qs = self.request.user.posts.all()
        return qs


class TagAutoComplete(autocomplete.Select2QuerySetView):
    def get_queryset(self):
        qs = Tag.objects.all()

        if self.q:
            qs = qs.filter(name__istartswith=self.q)

        return qs

    @method_decorator([login_required, blogger_required])
    def dispatch(self, request, *args, **kwargs):
        return super(TagAutoComplete, self).dispatch(request, *args, **kwargs)

tag_autocomplete = TagAutoComplete.as_view()


class UserPostsList(ListView):
    model = Post
    template_name = 'blog/user_posts.html'
    context_object_name = 'posts'

    @method_decorator([login_required, blogger_required])
    def dispatch(self, request, *args, **kwargs):
        return super(UserPostsList, self).dispatch(request, *args, **kwargs)

    def get_queryset(self):
        queryset = Post.objects.select_related(
            'author', 'blog').prefetch_related('tags').filter(author=self.request.user)  # noqa
        return queryset


class BlogComments(ListView):
    model = Comment
    template_name = 'blog/comments_list.html'
    context_object_name = 'comments'

    @method_decorator([login_required, blogger_required])
    def dispatch(self, request, *args, **kwargs):
        return super(BlogComments, self).dispatch(request, *args, **kwargs)

    def get_queryset(self):
        queryset = self.model.objects.select_related(
            'post', 'post__blog').filter(post__blog=self.request.user.blog)
        return queryset


class HomeTemplateView(ListView):
    template_name = 'blog/home.html'
    model = Post
    context_object_name = 'posts'

    def get_queryset(self):
        queryset = Post.objects.published().select_related(
            'author', 'author__profile', 'blog').prefetch_related(
                'tags').annotate(comment_count=Count('comments')).filter(blog__is_public=True)  # noqa
        return queryset

templates/blog/_post_list.html
{% load staticfiles %}
<div class="row">
  {% for post in posts %}
    <div class="col hide-on-med-and-down m4">
      <div class="post_detail" style="margin: 0px 10px; padding-right: 10px; border-right: 1px solid #dcdcdc">

        <p class="grey-text">
          <i class="material-icons left">mode_edit</i>
          <a href="{{ post.author.profile.get_absolute_url }}" class="grey-text">
            @{{ post.author.username }}
          </a>
        </p>

        <p class="grey-text">
          <i class="material-icons left">access_time</i>
          {{ post.created }}
        </p>

        <p class="grey-text">
          <i class="material-icons left">comment</i>
          {{ post.comment_count }}
        </p>

        <p class="grey-text"><i class="material-icons left">local_offer</i>
          {% for tag in post.tags.all %}
          <a href="{{ tag.get_absolute_url }}" class="grey-text">
            {{ tag.name }}</a>{% if not forloop.last %}, {% endif %}
          {% endfor %}
        </p>

      </div>
    </div>
    <div class="col s12 m8">
      <div class="card">
        <div class="card-image">
          {% if post.cover %}
            <img src="{{ post.cover.url }}">
          {% else %}
            <img src="{% static 'images/post-header.jpg' %}">
          {% endif %}
            <a href="{{ post.get_absolute_url }}">
            <span title="{{ post.title }}" class="card-title truncate"
            style="width: 100%; background: rgba(0,0,0,.3);">
              {{ post.title }}
            </span>
          </a>
        </div>
        <div class="card-content">
          <p>{{ post.summary }}</p>
        </div>
        <div class="card-action">
          <a href="{{ post.get_absolute_url }}">Read More</a>
        </div>
      </div>
    </div>
    {% empty %}
      <p class="grey-text">No posts found</a>
    {% endfor %}
</div>

templates/blog/blog_create_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block head_title %}Create a blog{% endblock %}

{% block content %}
  <div class="container">
    <h3 class="center">Start Blogging</h3>
      <div class="card-panel z-depth-0">
        {% crispy form %}
      </div>
  </div>
{% endblock %}

templates/blog/blog_detail.html
{% extends "base.html" %}

{% block head_title %}
  {% if not has_blog or not requested_user.blog.is_public %}
    No blog found
  {% else %}
    {{ requested_user.blog.title }} -- @{{ requested_user.username }}'s Blog
  {% endif %}
{% endblock %}

{% block content %}
  {% if not has_blog %}
    {% if user.id == requested_user.id %}
      <div id="no-blog-card" class="center flow-text">
        <div class="card">
          {% if requested_user.profile.is_blogger %}
            <div class="card-content">
              <span class="card-title">You haven't created a blog.</span>
              <p class="grey-text">Blogs are a nice way to show off your writing skills and documenting your life.
                <br/>You should give a try to it!</p>
            </div>
            <div class="card-action">
              <a href="{% url 'blog:blog_create' %}">Start blogging!</a>
            </div>
          {% else %}
            <div class="card-content">
              <span class="card-title">You are not a blogger</span>
              <p class="grey-text">You registered to medifeed as a reader, you can't have a blog.</p>
            </div>
            <div class="card-action">
              <a href="#">Contact the administrators.</a>
            </div>
          {% endif %}
          </div>
        </div>
    {% else %}
      <div id="no-blog-card" class="center flow-text">
        <div class="card">
            <div class="card-content">
              <span class="card-title">No blog found.</span>
              <p class="grey-text">This user doesn't seem to have a blog.</p>
            </div>
          </div>
        </div>
    {% endif %}
  {% elif not requested_user.blog.is_public %}
    <div id="no-blog-card" class="center flow-text">
      <div class="card">
          <div class="card-content">
            <span class="card-title">This blog is not publicly accessbile.</span>
            <p class="grey-text">This user doesn't want anyone to read his blog (strange, isn't it?).</p>
          </div>
        </div>
    </div>
  {% else %}
    <nav class="blue accent-2 z-depth-0">
      <div class="container">
      <div class="nav-wrapper row">
        <div class="col s12">
          <a href="/" class="breadcrumb">Home</a>
          <a href="{{ blog.author.profile.get_absolute_url }}" class="breadcrumb">@{{ blog.author.username }}</a>
          <span class="breadcrumb">{{ blog.title }}</span>
        </div>
      </div>
      </div>
    </nav>
    <div class="container">
      <h4 class="light" style="border-bottom: 1px solid #eee; padding-bottom: 10px; margin-top: 30px;">
        {{ requested_user.blog.title }}
      </h4>
      <p class="grey-text" style="font-size: 1.2em;">{{ requested_user.blog.tag_line }}</p>
      {% include "blog/_post_list.html" %}
    </div>
  {% endif %}
{% endblock %}

templates/blog/blog_update_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block head_title %}Update your blog{% endblock %}

{% block content %}
  <div class="container">
    <h3 class="center">Update your blog</h3>
      <div class="card-panel z-depth-0">
        {% crispy form %}
      </div>
  </div>
{% endblock %}

templates/blog/comments_list.html
{% extends "base.html" %}
{% block head_title %}Comments on your blog{% endblock %}

{% block content %}
<div class="container">
  <h4 class="light header">Comments</h4>
  {% for comment in comments %}
    <div class="card">
      <div class="card-content">
        <a href="{{ comment.post.get_absolute_url }}">
          <span title="{{ post.title }}" class="card-title truncate">
            {{ comment.post.title }}
          </span>
        </a>
        <p>{{ comment.comment }}</p>
      </div>
      <div class="card-action">
        <a href="{{ comment.get_absolute_url }}">View on post page</a>
      </div>
    </div>
  {% empty %}
    <p class="grey-text">No comments.</p>
  {% endfor %}
</div>
{% endblock %}

templates/blog/home.html
{% extends "base.html" %}

{% block head_title %}Home{% endblock %}

{% block content %}
  <div class="container">
    <h4 class="light header">Latest posts</h4>
    <p class="grey-text" style="font-size: 1.2em;">Stories which were just published recently.</p>
    {% include "blog/_post_list.html" %}
  </div>
{% endblock %}

templates/blog/post_create_form.html
{% extends "base.html" %}
{% load staticfiles %}
{% load crispy_forms_tags %}

{% block head_title %}Create a blogpost{% endblock %}

{% block content %}
  <div class="container">
    <h3 class="center">Create a blogpost</h3>
      <div class="card-panel z-depth-0">
        {% crispy form %}
      </div>
  </div>
{% endblock %}

{% block extra_scripts %}
    {{ form.media }}
    <link rel="stylesheet" href="{% static 'css/select2.materializecss.css' %}" charset="utf-8">
    <script type="text/javascript">
      $tag_label = $("label[for='id_tags']");
      $('#div_id_tags').hover(function () {
        $tag_label.toggleClass('hidden');
      })
    </script>
{% endblock %}

templates/blog/post_delete_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block head_title %}Delete a blogpost{% endblock %}

{% block content %}
  <div class="container">
    <h3 class="center">Delete: {{ post.title }}</h3>
      <div class="card-panel z-depth-1 center">
        <form method="post">
          <p>Do you really want to delete <b>{{ post.title }}</b>? This action is irreversible.</p>
          {% csrf_token %}
          {{ form|crispy }}
          <button type="submit" class="btn btn-large red waves-effect waves-light">
            Delete
          </button>
      </form>
      </div>
  </div>
{% endblock %}

templates/blog/post_detail.html
{% extends "base.html" %}
{% load comments_tags %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% load markdown_tags %}

{% block head_title %}
  {% if post.blog.is_public %}
    {{ post.title }} -- {{ post.blog.title }}
  {% else %}
    No blog found
  {% endif %}
{% endblock %}

{% block content %}
  {% if not post.blog.is_public %}
    <div id="no-blog-card" class="center flow-text">
      <div class="card">
          <div class="card-content">
            <span class="card-title">This blog is not publicly accessbile.</span>
            <p class="grey-text">This user doesn't want anyone to read his blog (strange, isn't it).</p>
          </div>
        </div>
    </div>
  {% else %}
  <nav class="blue accent-2 z-depth-0">
    <div class="container">
    <div class="nav-wrapper row">
      <div class="col s12">
        <a href="/" class="breadcrumb">Home</a>
        <a href="{{ post.author.profile.get_absolute_url }}" class="breadcrumb">
          @{{ post.author.username }}
        </a>
        <a href="{{ post.blog.get_absolute_url }}" class="breadcrumb">
          {{ post.blog.title }}
        </a>
        <span class="breadcrumb">{{ post.title }}</span>
      </div>
    </div>
    </div>
  </nav>
  <div class="container">
    <div class="card">
      <div class="card-image">
        {% if post.cover %}
          <img src="{{ post.cover.url }}">
        {% else %}
          <img src="{% static 'images/post-header.jpg' %}">
        {% endif %}
        <span class="card-title" style="width: 100%; background: rgba(0,0,0,.3);">{{ post.title }}</span>
      </div>
      <div class="card-content">
        <span class="left">@{{ post.author }}</span>
        <span class="right">{{ post.created }}</span>
      </div>
      <div class="card-content">
        <div class="post-content">
          {% render_markdown post.content %}
        </div>
      </div>
    </div>
    <div class="card">
      <div class="card-content">
        <div class="card-title">Tags</div>
        {% for tag in post.tags.all %}
        <a href="{{ tag.get_absolute_url }}" class="btn small grey">{{ tag.name }}</a>
        {% empty %}
          <p class="grey-text">No tags attached</p>
        {% endfor %}
      </div>
    </div>
    <div class="card">
      <div class="card-content" {% if user.is_authenticated %}style="height:280px;"{% endif %}>
        <div class="card-title">Post a comment</div>
        {% if user.is_authenticated %}
          {% get_comment_form post as comment_form %}
          {% crispy comment_form %}
        {% else %}
          <p>Only logged in users can comment on blog posts.
            Click here to Login or Signup today if you don't have an account yet.</p>
        {% endif %}
      </div>
    </div>
    <h4 class="light header">Comments</h4>
    {% get_comment_list post as post_comments %}
      <ul class="user-comments">
        {% for comment in post_comments %}
        <li data-comment-id="{{ comment.id }}" class="c" id="c{{ comment.id }}">
          <div class="card">
            <div class="card-content">
              <a href="{% url 'authapp:profile' comment.author.username %}">
                <span title="{{ comment.author.first_name }}" class="card-title truncate">
                  {{ comment.author.first_name }}
                </span>
              </a>
              <p>{{ comment.comment }}</p>
            </div>
            <div class="card-panel">
              <i class="material-icons left">access_time</i>
              <a href="#c{{ comment.id }}" class="comment-datetime"
              data-datetime="{{ comment.created|date:"c" }}">{{ comment.created }}</a>
            </div>
          </div>
        </li>
        {% empty %}
          <p class="grey-text no-comment-string">No comments.</p>
        {% endfor %}
    </ul>
  </div>
  {% endif %}

{% endblock %}

{% block extra_scripts %}
  <script type="text/javascript" src="{% static 'js/comments.js' %}"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/mustache.js/2.2.1/mustache.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.11.2/moment.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/moment-timezone/0.5.0/moment-timezone-with-data-2010-2020.min.js"></script>

{% verbatim %}
  <script type="text/html" id="comment-item">
    <li data-comment-id="{{ id }}" class="c" id="c{{ id }}">
      <div class="card">
        <div class="card-content">
          <a href="{{ link }}">
            <span title="{{ name }}" class="card-title truncate">
              {{ name}}
            </span>
          </a>
          <p>{{ comment }}</p>
        </div>
        <div class="card-panel">
          <i class="material-icons left">access_time</i>
          <a href="#c{{ id }}" class="comment-datetime">{{ created }}</a>
        </div>
      </div>
    </li>
  </script>
{% endverbatim %}

  <script type="text/javascript">
      var $dt = $('.comment-datetime');
      $.each($dt, function (i, datetime) {
          $(this).html(moment($(this).attr('data-datetime')).format('LLL'));
      });
  </script>


{% endblock %}

templates/blog/post_update_form.html
{% extends "base.html" %}
{% load staticfiles %}
{% load crispy_forms_tags %}

{% block head_title %}Update: {{ post.title }}{% endblock %}

{% block content %}
  <div class="container">
    <h3 class="center"><b>Update</b>: {{ post.title }}</h3>
      <div class="card-panel z-depth-0">
        {% crispy form %}
      </div>
  </div>
{% endblock %}

{% block extra_scripts %}
    {{ form.media }}
    <link rel="stylesheet" href="{% static 'css/select2.materializecss.css' %}" charset="utf-8">
    <script type="text/javascript">
      $tag_label = $("label[for='id_tags']");
      $('#div_id_tags').hover(function () {
        $tag_label.toggleClass('hidden');
      })
    </script>
{% endblock %}

templates/blog/tagged_posts_list.html
{% extends "base.html" %}
{% block head_title %}{{ tag }} posts{% endblock %}

{% block content %}
<div class="container">
  <h4 class="light header">{{ tag }}</h4>
  <p class="grey-text" style="font-size: 1.2em;">Stories about {{ tag }}.</p>
  {% include "blog/_post_list.html" %}
</div>
{% endblock %}

templates/blog/user_posts.html
{% extends "base.html" %}
{% load staticfiles %}
{% block head_title %}Your posts{% endblock %}

{% block content %}
  <div class="container">
    <h4 class="light" style="border-bottom: 1px solid #eee; padding-bottom: 10px; margin-top: 30px;">Your blog posts</h4>
    <div class="row">
      {% for post in posts %}
        <div class="col hide-on-med-and-down m4">
          <div style="margin: 0px 10px; padding-right: 10px; border-right: 1px solid #dcdcdc">
            <p class="grey-text">{% if post.is_published %}PUBLISHED{% else %}DRAFT{% endif %}</p>
            <p class="grey-text"><i class="material-icons left">access_time</i> {{ post.created }}</p>
            <p class="grey-text"><i class="material-icons left">local_offer</i> {% for tag in post.tags.all %}
              {{ tag.name }}{% if not forloop.last %}, {% endif %}
              {% endfor %}</p>
          </div>
        </div>
        <div class="col s12 m8">
          <div class="card">
            <div class="card-image">
              {% if post.cover %}
                <img src="{{ post.cover.url }}">
              {% else %}
                <img src="{% static 'images/post-header.jpg' %}">
              {% endif %}
                <a href="{% url 'blog:post_detail' user.username post.slug %}">
                <span title="{{ post.title }}" class="card-title truncate" style="width: 100%; background: rgba(0,0,0,.3);">{{ post.title }}</span></a>
            </div>
            <div class="card-content">
              <p>{{ post.summary }}</p>
            </div>
            <div class="card-action">
              <a href="{% url 'blog:post_update' post.slug %}">Edit</a>
              <a href="{% url 'blog:post_delete' post.slug %}">Delete</a>
            </div>
          </div>
        </div>
      {% empty %}
        <p class="grey-text">No posts found</a>
      {% endfor %}
      </div>
    </div>
{% endblock %}