blog/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.HomeTemplateView.as_view(), name='home'),
    url(r'^@(?P<username>[\w-]+)/blog/$', views.BlogDetail.as_view(), name='user_blog'),  # noqa
    url(r'^@(?P<username>[\w-]+)/blog/(?P<slug>[\w-]+)/$',
        views.PostDetailView.as_view(), name='post_detail'),

    url(r'^tags/$', views.TagAutoComplete.as_view(), name='tag_autocomplete'),
    url(r'^tags/(?P<tag>[\w-]+)/$', views.TagggedPostsList.as_view(),
        name='tagged_posts_list'),

    url(r'^blog/start/$', views.BlogCreateView.as_view(), name='blog_create'),
    url(r'^blog/update/$', views.BlogUpdateView.as_view(), name='blog_update'),

    url(r'^blog/comments/$', views.BlogComments.as_view(), name='blog_comments'),  # noqa

    url(r'^write/$', views.PostCreateView.as_view(), name='post_create'),
    url(r'^update/(?P<slug>[\w-]+)/$', views.PostUpdateView.as_view(), name='post_update'),  # noqa
    url(r'^delete/(?P<slug>[\w-]+)/$', views.PostDeleteView.as_view(), name='post_delete'),  # noqa

    url(r'^posts/$', views.UserPostsList.as_view(), name='user_posts'),
]

medifeed/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^simplemde/', include('simplemde.urls', namespace='simplemde')),
    url(r'^comments/', include('comments.urls', namespace='comments')),
    url(r'^', include('authapp.urls', namespace='authapp')),
    url(r'^', include('blog.urls', namespace='blog')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # noqa

templates/_footer.html
<footer class="page-footer blue accent-2">
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
       <!--  <h5 class="white-text">About</h5>
        <p class="grey-text text-lighten-4">
          This project is part of qwikpik internship assignment.
          <br/>
          It was written by <a href="https://www.github.com/v1k45/" title="Vikas Yadav" class="white-text">v1k45</p> -->
      </div>
    </div>
  </div>
  <div class="footer-copyright">
   <!--  <div class="container">
    Made with &lt;3 using <a class="white-text" href="http://materializecss.com">Materialize</a>
    </div> -->
  </div>
</footer>

templates/_navbar.html
{% load staticfiles %}
<div class="navbar-fixed">
  <nav role="navigation" class="blue">
    <div class="nav-wrapper container">
      <a id="logo-container" href="/" class="brand-logo">medifeed</a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li><a href="/">Home</a></li>
        {% if user.is_authenticated %}
          <li>
            <a href="{% url 'authapp:user_profile' %}" class="dropdown-button"
              data-activates="user-dropdown" data-beloworigin="true" data-constrainwidth="false">
              hey, @{{ user.username }} <i class="material-icons right">arrow_drop_down</i>
            </a>
              <!-- user dropdown -->
              <ul id="user-dropdown" class="dropdown-content">
                <li>
                  <a href="{% url 'authapp:user_profile' %}">View profile</a>
                </li>
                <li>
                  <a href="{% url 'account_change_password' %}">Change pasword</a>
                </li>
                <li class="divider"></li>
                <li>
                  <a href="{% url 'account_logout' %}">Log out</a>
                </li>
              </ul>
          </li>
        {% else %}
          <li><a href="{% url 'account_login' %}">Login</a></li>
          <li><a href="{% url 'account_signup' %}" class="btn purple waves-effect waves-light">Sign Up</a></li>
        {% endif %}
      </ul>
      <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
    </div>
  </nav>
</div>

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block head_title %}{% endblock %} | medifeed</title>
    <!-- Compiled and minified CSS -->
    <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/css/materialize.min.css">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    {# block to easily inject any content in head #}
    {% block extra_head %}
    {% endblock %}
  </head>
  <body>
    <header>
    {# include navbar #}
    {% include "_navbar.html" %}
    </header>
    <main>
      {% block content %}
      {% endblock %}
    </main>

    {% if user.is_authenticated and user.profile.is_blogger %}
      <div class="fixed-action-btn" style="bottom: 45px; right: 24px;">
        <a class="btn-floating btn-large red">
          <i class="large material-icons">add</i>
        </a>
        <ul>
          <li><a href="{% url 'blog:blog_update' %}" class="btn-floating red tooltipped" data-position="left"
                data-delay="50" data-tooltip="Update blog info">
                <i class="material-icons">info</i></a></li>
          <li><a href="{% url 'blog:blog_comments' %}" class="btn-floating purpule tooltipped" data-position="left"
                data-delay="50" data-tooltip="View blog comments">
            <i class="material-icons">comment</i></a></li>
          <li><a href="{% url 'blog:user_posts' %}" class="btn-floating green tooltipped" data-position="left"
                data-delay="50" data-tooltip="All blogposts">
                <i class="material-icons">library_books</i></a></li>
          <li><a href="{% url 'blog:post_create' %}" class="btn-floating blue tooltipped" data-position="left"
            data-delay="50" data-tooltip="Write a post">
            <i class="material-icons">mode_edit</i></a></li>
        </ul>
      </div>
    {% endif %}

    {# include footer #}
    {% include "_footer.html" %}
    <!-- start javascript inclusions -->
    <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/js/materialize.min.js"></script>
    <script type="text/javascript" src="{% static 'js/csrf.js' %}"></script>
    <script type="text/javascript">
      $(document).ready(function(){
        $(".dropdown-button").dropdown();
      });
    </script>

    <!-- alerts -->
    {% if messages %}
        <script type="text/javascript">
            $(document).ready(function () {
                {% for message in messages %}
                    Materialize.toast('{{ message }}', 5000, '{{ message.tags }}');
                {% endfor %}
            });
        </script>
    {% endif %}
    <!-- end alerts -->

    {# block to easily inject any javascript content #}
    {% block extra_scripts %}
    {% endblock %}
    <!-- end javascript inclusions -->
  </body>
</html>